20-03-21 13:40-INFO-{'session_length': 24, 'height': 32, 'width': 32, 'num_labels': 13, 'learning_rate': 0.0005, 'filter_sizes': [3, 4, 5, 6], 'num_filters': 64, 'filter_sizes_hierarchical': [3, 4, 5], 'num_fitlers_hierarchical': 64, 'is_train': True, 'early_stop': True, 'is_pretrain': False, 'is_time': False, 'is_size': False, 'uncertainty': False, 'is_tuning': True}
20-03-21 13:40-WARNING-From ../utils.py:127: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

20-03-21 13:40-WARNING-From ../model/train.py:79: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

20-03-21 13:40-WARNING-From ../model/base_model.py:46: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

20-03-21 13:40-WARNING-From ../model/hierarchical_model.py:46: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

20-03-21 13:40-WARNING-From ../model/hierarchical_model.py:46: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

20-03-21 13:40-WARNING-From ../model/utils/utils.py:25: conv1d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv1D` instead.
20-03-21 13:40-WARNING-Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f1359832310>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f1359832310>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-From ../model/utils/utils.py:44: max_pooling1d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.MaxPooling1D instead.
20-03-21 13:40-WARNING-Entity <bound method Pooling1D.call of <tensorflow.python.layers.pooling.MaxPooling1D object at 0x7f135983a550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling1D.call of <tensorflow.python.layers.pooling.MaxPooling1D object at 0x7f135983a550>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f135983a690>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f135983a690>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-Entity <bound method Pooling1D.call of <tensorflow.python.layers.pooling.MaxPooling1D object at 0x7f13662262d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling1D.call of <tensorflow.python.layers.pooling.MaxPooling1D object at 0x7f13662262d0>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f1359832550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f1359832550>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-Entity <bound method Pooling1D.call of <tensorflow.python.layers.pooling.MaxPooling1D object at 0x7f1359832e10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling1D.call of <tensorflow.python.layers.pooling.MaxPooling1D object at 0x7f1359832e10>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f1359832450>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f1359832450>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-Entity <bound method Pooling1D.call of <tensorflow.python.layers.pooling.MaxPooling1D object at 0x7f1359832e10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling1D.call of <tensorflow.python.layers.pooling.MaxPooling1D object at 0x7f1359832e10>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-From ../model/utils/modules.py:207: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dropout instead.
20-03-21 13:40-WARNING-Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f135b620350>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f135b620350>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-Variable *= will be deprecated. Use `var.assign(var * other)` if you want assignment to the variable value or `x = x * y` if you want a new python Tensor object.
20-03-21 13:40-WARNING-Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f1358c48950>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f1358c48950>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-Entity <bound method Pooling1D.call of <tensorflow.python.layers.pooling.MaxPooling1D object at 0x7f1358b5f8d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling1D.call of <tensorflow.python.layers.pooling.MaxPooling1D object at 0x7f1358b5f8d0>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f1358c26c90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f1358c26c90>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-Entity <bound method Pooling1D.call of <tensorflow.python.layers.pooling.MaxPooling1D object at 0x7f1358c48950>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling1D.call of <tensorflow.python.layers.pooling.MaxPooling1D object at 0x7f1358c48950>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f1358c1fe90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f1358c1fe90>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-Entity <bound method Pooling1D.call of <tensorflow.python.layers.pooling.MaxPooling1D object at 0x7f1358c1ff10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling1D.call of <tensorflow.python.layers.pooling.MaxPooling1D object at 0x7f1358c1ff10>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-From ../model/utils/modules.py:242: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
20-03-21 13:40-WARNING-Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f1358bd6790>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f1358bd6790>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-From ../model/utils/modules.py:244: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).
20-03-21 13:40-WARNING-Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f1358c49510>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f1358c49510>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-From ../model/utils/modules.py:247: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
20-03-21 13:40-WARNING-Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f1358bb0890>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f1358bb0890>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f1359795590>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f1359795590>>: AssertionError: Bad argument number for Name: 3, expecting 4
20-03-21 13:40-WARNING-From ../model/base_model.py:130: The name tf.train.GradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.GradientDescentOptimizer instead.

20-03-21 13:40-WARNING-From /root/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/clip_ops.py:286: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
20-03-21 13:40-WARNING-From ../model/train.py:88: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

20-03-21 13:40-WARNING-From /root/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
20-03-21 13:40-INFO-Restoring parameters from /root/data/mentali/IDS/ckpt/hierarchical_cnn_pretrain/hierarchical_cnn-6252
20-03-21 13:42-INFO-Epoch 0, Batch 100, Global step 100:
20-03-21 13:42-INFO-training batch loss: 2.5025; avg_loss: 2.5350
20-03-21 13:42-INFO-training batch accuracy: 0.3125; avg_accuracy: 0.3623
20-03-21 13:42-INFO-
20-03-21 13:44-INFO-Epoch 0, Batch 200, Global step 200:
20-03-21 13:44-INFO-training batch loss: 2.2191; avg_loss: 2.4632
20-03-21 13:44-INFO-training batch accuracy: 0.3750; avg_accuracy: 0.3679
20-03-21 13:44-INFO-
20-03-21 13:46-INFO-Epoch 0, Batch 300, Global step 300:
20-03-21 13:46-INFO-training batch loss: 1.6846; avg_loss: 2.2914
20-03-21 13:46-INFO-training batch accuracy: 0.3672; avg_accuracy: 0.3708
20-03-21 13:46-INFO-
20-03-21 13:48-INFO-Epoch 0, Batch 400, Global step 400:
20-03-21 13:48-INFO-training batch loss: 1.4948; avg_loss: 2.1018
20-03-21 13:48-INFO-training batch accuracy: 0.3281; avg_accuracy: 0.3710
20-03-21 13:48-INFO-
20-03-21 13:50-INFO-Epoch 0, Batch 500, Global step 500:
20-03-21 13:50-INFO-training batch loss: 1.4270; avg_loss: 1.9593
20-03-21 13:50-INFO-training batch accuracy: 0.3359; avg_accuracy: 0.3742
20-03-21 13:50-INFO-
20-03-21 13:52-INFO-Epoch 0, Batch 600, Global step 600:
20-03-21 13:52-INFO-training batch loss: 1.3170; avg_loss: 1.8575
20-03-21 13:52-INFO-training batch accuracy: 0.4062; avg_accuracy: 0.3789
20-03-21 13:52-INFO-
20-03-21 13:54-INFO-Epoch 0, Batch 700, Global step 700:
20-03-21 13:54-INFO-training batch loss: 1.3380; avg_loss: 1.7797
20-03-21 13:54-INFO-training batch accuracy: 0.5078; avg_accuracy: 0.3850
20-03-21 13:54-INFO-
20-03-21 13:56-INFO-Epoch 0, Batch 800, Global step 800:
20-03-21 13:56-INFO-training batch loss: 1.3425; avg_loss: 1.7207
20-03-21 13:56-INFO-training batch accuracy: 0.5547; avg_accuracy: 0.4047
20-03-21 13:56-INFO-
20-03-21 13:58-INFO-Epoch 0, Batch 900, Global step 900:
20-03-21 13:58-INFO-training batch loss: 1.3130; avg_loss: 1.6727
20-03-21 13:58-INFO-training batch accuracy: 0.5859; avg_accuracy: 0.4199
20-03-21 13:58-INFO-
20-03-21 14:00-INFO-Epoch 0, Batch 1000, Global step 1000:
20-03-21 14:00-INFO-training batch loss: 1.2745; avg_loss: 1.6333
20-03-21 14:00-INFO-training batch accuracy: 0.5859; avg_accuracy: 0.4327
20-03-21 14:00-INFO-
20-03-21 14:02-INFO-Epoch 0, Batch 1100, Global step 1100:
20-03-21 14:02-INFO-training batch loss: 1.3018; avg_loss: 1.6006
20-03-21 14:02-INFO-training batch accuracy: 0.5078; avg_accuracy: 0.4435
20-03-21 14:02-INFO-
20-03-21 14:04-INFO-Epoch 0, Batch 1200, Global step 1200:
20-03-21 14:04-INFO-training batch loss: 1.3418; avg_loss: 1.5715
20-03-21 14:04-INFO-training batch accuracy: 0.4609; avg_accuracy: 0.4525
20-03-21 14:04-INFO-
20-03-21 14:06-INFO-Epoch 0, Batch 1300, Global step 1300:
20-03-21 14:06-INFO-training batch loss: 1.2677; avg_loss: 1.5459
20-03-21 14:06-INFO-training batch accuracy: 0.5234; avg_accuracy: 0.4608
20-03-21 14:06-INFO-
